package catalog

type Category string

const (
	CategoryStanding  Category = "standing"
	CategorySeated    Category = "seated"
	CategoryProne     Category = "prone"
	CategorySupine    Category = "supine"
	CategoryInversion Category = "inversion"
)

type Pose struct {
	PoseID            string   `json:"pose_id"`
	NameEN            string   `json:"name_en"`
	NameTR            string   `json:"name_tr"`
	Category          Category `json:"category"`
	Difficulty        int      `json:"difficulty"`
	TargetArea        string   `json:"target_area"`
	InstructionsEN    string   `json:"instructions_en"`
	InstructionsTR    string   `json:"instructions_tr"`
	Contraindications []string `json:"contraindications"`
}

var AllPoses = []Pose{
	{PoseID: "mountain", NameEN: "Mountain Pose", NameTR: "Dağ Duruşu", Category: CategoryStanding, Difficulty: 1, TargetArea: "full_body", InstructionsEN: "Stand tall with feet together, arms at sides. Distribute weight evenly, engage thighs, lengthen spine. Relax shoulders down and breathe deeply.", InstructionsTR: "Ayaklar bitişik, kollar yanlarda dik durun. Ağırlığı eşit dağıtın, baldırları sıkın, omurgayı uzatın. Omuzları gevşetin ve derin nefes alın.", Contraindications: []string{}},
	{PoseID: "forward_fold", NameEN: "Standing Forward Fold", NameTR: "Ayakta Öne Eğilme", Category: CategoryStanding, Difficulty: 1, TargetArea: "hamstrings", InstructionsEN: "From standing, hinge at hips and fold forward. Let head hang heavy, bend knees slightly if needed. Hold opposite elbows and sway gently.", InstructionsTR: "Ayakta duruştan kalçalardan öne doğru katlayın. Başı serbest bırakın, gerekirse dizleri hafifçe bükün. Dirseklerden tutup hafifçe sallanın.", Contraindications: []string{"herniated_disc", "low_back_pain"}},
	{PoseID: "warrior_1", NameEN: "Warrior I", NameTR: "Savaşçı I", Category: CategoryStanding, Difficulty: 2, TargetArea: "legs", InstructionsEN: "Step one foot back, bend front knee to 90 degrees. Square hips forward, raise arms overhead. Press back heel firmly into the mat.", InstructionsTR: "Bir ayağı geriye atın, ön dizi 90 derece bükün. Kalçaları öne hizalayın, kolları yukarı kaldırın. Arka topuğu yere sıkıca basın.", Contraindications: []string{"knee_injury"}},
	{PoseID: "warrior_2", NameEN: "Warrior II", NameTR: "Savaşçı II", Category: CategoryStanding, Difficulty: 2, TargetArea: "legs", InstructionsEN: "Step feet wide apart, turn front foot out 90 degrees. Bend front knee over ankle, extend arms parallel to floor. Gaze over front fingertips.", InstructionsTR: "Ayakları geniş açın, ön ayağı 90 derece dışa çevirin. Ön dizi bilek üzerine bükün, kolları yere paralel uzatın. Bakışları ön parmak uçlarına yöneltin.", Contraindications: []string{"knee_injury"}},
	{PoseID: "warrior_3", NameEN: "Warrior III", NameTR: "Savaşçı III", Category: CategoryStanding, Difficulty: 4, TargetArea: "balance", InstructionsEN: "From standing, hinge forward at hips while lifting one leg behind. Arms extend forward, body forms a T-shape. Keep standing leg strong and hips level.", InstructionsTR: "Ayakta duruştan kalçalardan öne eğilirken bir bacağı arkaya kaldırın. Kollar öne uzanır, vücut T şekli oluşturur. Duran bacağı güçlü tutun, kalçaları hizada tutun.", Contraindications: []string{"knee_injury", "ankle_injury"}},
	{PoseID: "triangle", NameEN: "Triangle Pose", NameTR: "Üçgen Duruşu", Category: CategoryStanding, Difficulty: 2, TargetArea: "legs", InstructionsEN: "Step feet wide, turn front foot out. Extend torso over front leg, lower hand to shin or floor. Top arm reaches to ceiling.", InstructionsTR: "Ayakları geniş açın, ön ayağı dışa çevirin. Gövdeyi ön bacak üzerine uzatın, eli baldıra veya yere indirin. Üst kol tavana uzanır.", Contraindications: []string{"low_back_pain"}},
	{PoseID: "extended_side_angle", NameEN: "Extended Side Angle", NameTR: "Uzatılmış Yan Açı", Category: CategoryStanding, Difficulty: 2, TargetArea: "legs", InstructionsEN: "From Warrior II, bring front forearm to front thigh or hand to floor. Extend top arm over ear creating one long line from back foot to fingertips.", InstructionsTR: "Savaşçı II'den ön kolu ön uyluğa veya eli yere indirin. Üst kolu kulak üzerinden uzatarak arka ayaktan parmak uçlarına tek bir çizgi oluşturun.", Contraindications: []string{"knee_injury"}},
	{PoseID: "tree", NameEN: "Tree Pose", NameTR: "Ağaç Duruşu", Category: CategoryStanding, Difficulty: 2, TargetArea: "balance", InstructionsEN: "Stand on one leg, place other foot on inner thigh or calf (never on knee). Bring hands to prayer or overhead. Fix gaze on a steady point.", InstructionsTR: "Tek bacak üzerinde durun, diğer ayağı iç uyluğa veya baldıra yerleştirin (asla dize değil). Elleri namaz pozisyonuna veya yukarı getirin. Bakışları sabit bir noktaya odaklayın.", Contraindications: []string{"ankle_injury"}},
	{PoseID: "chair", NameEN: "Chair Pose", NameTR: "Sandalye Duruşu", Category: CategoryStanding, Difficulty: 2, TargetArea: "legs", InstructionsEN: "Stand with feet together, bend knees as if sitting in a chair. Keep knees behind toes, raise arms overhead. Engage core and lengthen tailbone down.", InstructionsTR: "Ayaklar bitişik, dizleri sandalyeye oturur gibi bükün. Dizleri parmak uçlarının gerisinde tutun, kolları yukarı kaldırın. Karnı sıkın ve kuyruk kemiğini aşağı uzatın.", Contraindications: []string{"knee_injury"}},
	{PoseID: "half_moon", NameEN: "Half Moon Pose", NameTR: "Yarım Ay Duruşu", Category: CategoryStanding, Difficulty: 3, TargetArea: "balance", InstructionsEN: "From Triangle, bend front knee and shift weight forward. Lift back leg parallel to floor, open hips and chest to the side. Bottom hand on floor or block.", InstructionsTR: "Üçgen duruşundan ön dizi bükün ve ağırlığı öne kaydırın. Arka bacağı yere paralel kaldırın, kalça ve göğsü yana açın. Alt el yerde veya blokta.", Contraindications: []string{"low_back_pain", "ankle_injury"}},
	{PoseID: "eagle", NameEN: "Eagle Pose", NameTR: "Kartal Duruşu", Category: CategoryStanding, Difficulty: 3, TargetArea: "balance", InstructionsEN: "Wrap one leg over the other, cross arms at elbows and wrists. Sink hips down, lift elbows up. Focus on a fixed point for balance.", InstructionsTR: "Bir bacağı diğerinin üzerine sarın, kolları dirsek ve bileklerden çaprazlayın. Kalçaları aşağı indirin, dirsekleri yukarı kaldırın. Denge için sabit bir noktaya odaklanın.", Contraindications: []string{"knee_injury", "shoulder_injury"}},
	{PoseID: "dancer", NameEN: "Dancer Pose", NameTR: "Dansçı Duruşu", Category: CategoryStanding, Difficulty: 4, TargetArea: "balance", InstructionsEN: "Stand on one leg, grab opposite foot behind you. Press foot into hand and lean forward, extending free arm ahead. Open chest and hold balance.", InstructionsTR: "Tek bacak üzerinde durun, karşı ayağı arkanızdan tutun. Ayağı ele doğru bastırın ve öne eğilin, serbest kolu öne uzatın. Göğsü açın ve dengeyi koruyun.", Contraindications: []string{"ankle_injury", "low_back_pain"}},
	{PoseID: "high_lunge", NameEN: "High Lunge", NameTR: "Yüksek Hamle", Category: CategoryStanding, Difficulty: 2, TargetArea: "legs", InstructionsEN: "Step one foot back, bend front knee to 90 degrees. Back heel lifted, arms reach overhead. Keep core engaged and hips square.", InstructionsTR: "Bir ayağı geriye atın, ön dizi 90 derece bükün. Arka topuk havada, kollar yukarı uzanır. Karnı sıkı ve kalçaları hizada tutun.", Contraindications: []string{"knee_injury"}},
	{PoseID: "crescent_lunge", NameEN: "Crescent Lunge", NameTR: "Hilal Hamle", Category: CategoryStanding, Difficulty: 2, TargetArea: "hip_flexors", InstructionsEN: "From High Lunge, gently arch back, lifting chest and reaching arms up and slightly back. Deepen the stretch in hip flexors. Breathe steadily.", InstructionsTR: "Yüksek Hamle'den hafifçe arkaya kavis yapın, göğsü kaldırın ve kolları yukarı ve hafifçe geriye uzatın. Kalça fleksörlerinde gerilmeyi derinleştirin. Düzenli nefes alın.", Contraindications: []string{"knee_injury"}},
	{PoseID: "wide_leg_forward_fold", NameEN: "Wide-Legged Forward Fold", NameTR: "Geniş Bacak Öne Eğilme", Category: CategoryStanding, Difficulty: 2, TargetArea: "hamstrings", InstructionsEN: "Step feet wide apart, toes slightly inward. Fold forward from hips, bring hands to floor or hold ankles. Keep legs strong and spine long.", InstructionsTR: "Ayakları geniş açın, parmak uçları hafif içe dönük. Kalçalardan öne katlayın, elleri yere veya bileklere getirin. Bacakları güçlü ve omurgayı uzun tutun.", Contraindications: []string{"herniated_disc"}},
	{PoseID: "goddess", NameEN: "Goddess Pose", NameTR: "Tanrıça Duruşu", Category: CategoryStanding, Difficulty: 2, TargetArea: "legs", InstructionsEN: "Step feet wide, turn toes out 45 degrees. Bend knees over ankles into a deep squat. Arms at shoulder height with elbows bent, palms forward.", InstructionsTR: "Ayakları geniş açın, parmak uçlarını 45 derece dışa çevirin. Dizleri bilekler üzerine bükün ve derin çömelin. Kollar omuz hizasında, dirsekler bükülü, avuçlar öne bakıyor.", Contraindications: []string{"knee_injury"}},
	{PoseID: "standing_split", NameEN: "Standing Split", NameTR: "Ayakta Spagat", Category: CategoryStanding, Difficulty: 4, TargetArea: "hamstrings", InstructionsEN: "From forward fold, lift one leg high behind you. Keep hips square and standing leg straight. Hands on floor or blocks for support.", InstructionsTR: "Öne eğilmeden bir bacağı arkaya doğru yükseğe kaldırın. Kalçaları hizada ve duran bacağı düz tutun. Eller yerde veya bloklarda destek için.", Contraindications: []string{"hamstring_injury", "low_back_pain"}},

	{PoseID: "seated_forward_fold", NameEN: "Seated Forward Fold", NameTR: "Oturarak Öne Eğilme", Category: CategorySeated, Difficulty: 1, TargetArea: "hamstrings", InstructionsEN: "Sit with legs extended, flex feet. Hinge forward from hips reaching for feet or shins. Keep spine long, avoid rounding the back.", InstructionsTR: "Bacaklar uzatılmış oturun, ayakları esnetin. Kalçalardan öne eğilin, ayaklara veya baldırlara uzanın. Omurgayı uzun tutun, sırtı yuvarlaklaştırmayın.", Contraindications: []string{"herniated_disc"}},
	{PoseID: "easy_seat", NameEN: "Easy Seat", NameTR: "Kolay Oturuş", Category: CategorySeated, Difficulty: 1, TargetArea: "hips", InstructionsEN: "Sit cross-legged with spine tall. Rest hands on knees, relax shoulders. Close eyes and breathe deeply into the belly.", InstructionsTR: "Bağdaş kurup omurga dik oturun. Elleri dizlere koyun, omuzları gevşetin. Gözleri kapatın ve karnınıza doğru derin nefes alın.", Contraindications: []string{}},
	{PoseID: "bound_angle", NameEN: "Bound Angle Pose", NameTR: "Bağlı Açı Duruşu", Category: CategorySeated, Difficulty: 1, TargetArea: "hips", InstructionsEN: "Sit with soles of feet together, knees out to sides. Hold feet and gently press knees toward floor. Sit tall and breathe.", InstructionsTR: "Ayak tabanları birleşik, dizler yanlara açık oturun. Ayakları tutun ve dizleri yere doğru hafifçe bastırın. Dik oturun ve nefes alın.", Contraindications: []string{"groin_injury"}},
	{PoseID: "head_to_knee", NameEN: "Head-to-Knee Pose", NameTR: "Baş-Diz Duruşu", Category: CategorySeated, Difficulty: 2, TargetArea: "hamstrings", InstructionsEN: "Sit with one leg extended, other foot to inner thigh. Fold over extended leg reaching for foot. Keep spine long.", InstructionsTR: "Bir bacak uzatılmış, diğer ayak iç uyluğa dayalı oturun. Uzatılmış bacak üzerine katlayın ve ayağa uzanın. Omurgayı uzun tutun.", Contraindications: []string{"herniated_disc", "knee_injury"}},
	{PoseID: "half_lord_of_fishes", NameEN: "Half Lord of the Fishes", NameTR: "Yarım Balıkların Efendisi", Category: CategorySeated, Difficulty: 2, TargetArea: "spine", InstructionsEN: "Sit with one leg crossed over the other. Twist torso toward the top knee, using opposite elbow for leverage. Lengthen spine with each inhale.", InstructionsTR: "Bir bacağı diğerinin üzerinden geçirerek oturun. Gövdeyi üst dize doğru döndürün, karşı dirseği kaldıraç olarak kullanın. Her nefeste omurgayı uzatın.", Contraindications: []string{"herniated_disc", "spinal_injury"}},
	{PoseID: "hero", NameEN: "Hero Pose", NameTR: "Kahraman Duruşu", Category: CategorySeated, Difficulty: 2, TargetArea: "quadriceps", InstructionsEN: "Kneel with knees together, sit between heels. Keep spine tall and hands on thighs. Use a block under seat if needed for comfort.", InstructionsTR: "Dizler bitişik diz çökün, topuklar arasına oturun. Omurgayı dik tutun, eller uyluklar üzerinde. Gerekirse oturağın altına blok koyun.", Contraindications: []string{"knee_injury"}},
	{PoseID: "cow_face", NameEN: "Cow Face Pose", NameTR: "İnek Yüzü Duruşu", Category: CategorySeated, Difficulty: 3, TargetArea: "shoulders", InstructionsEN: "Stack knees and sit between heels. Reach one arm overhead and the other behind your back, clasp fingers. Sit tall and open the chest.", InstructionsTR: "Dizleri üst üste getirin ve topuklar arasına oturun. Bir kolu yukarıdan, diğerini sırt arkasından uzatın ve parmakları kavuşturun. Dik oturun ve göğsü açın.", Contraindications: []string{"shoulder_injury", "knee_injury"}},
	{PoseID: "pigeon", NameEN: "Pigeon Pose", NameTR: "Güvercin Duruşu", Category: CategorySeated, Difficulty: 3, TargetArea: "hips", InstructionsEN: "From Downward Dog, bring one knee forward behind wrist. Extend opposite leg back. Walk hands forward and lower torso over front shin.", InstructionsTR: "Aşağı Bakan Köpek'ten bir dizi bileğin arkasına getirin. Karşı bacağı geriye uzatın. Elleri öne yürütün ve gövdeyi ön baldır üzerine indirin.", Contraindications: []string{"knee_injury", "hip_injury"}},
	{PoseID: "fire_log", NameEN: "Fire Log Pose", NameTR: "Ateş Kütüğü Duruşu", Category: CategorySeated, Difficulty: 3, TargetArea: "hips", InstructionsEN: "Stack shins on top of each other with feet outside opposite knees. Sit tall and fold forward for a deeper stretch in hips.", InstructionsTR: "Baldırları üst üste koyun, ayaklar karşı dizlerin dışında. Dik oturun ve kalçalarda daha derin gerilme için öne katlayın.", Contraindications: []string{"knee_injury"}},
	{PoseID: "lotus", NameEN: "Lotus Pose", NameTR: "Lotus Duruşu", Category: CategorySeated, Difficulty: 4, TargetArea: "hips", InstructionsEN: "Sit cross-legged and place each foot on the opposite thigh. Rest hands on knees in mudra. Keep spine tall and breathe deeply.", InstructionsTR: "Bağdaş kurup her ayağı karşı uyluğun üzerine yerleştirin. Elleri dizlerde mudra pozisyonunda tutun. Omurgayı dik tutun ve derin nefes alın.", Contraindications: []string{"knee_injury", "ankle_injury"}},
	{PoseID: "staff", NameEN: "Staff Pose", NameTR: "Asa Duruşu", Category: CategorySeated, Difficulty: 1, TargetArea: "core", InstructionsEN: "Sit with legs extended straight ahead, feet flexed. Place hands beside hips, press palms into floor. Sit tall, engaging core muscles.", InstructionsTR: "Bacaklar düz öne uzatılmış, ayaklar esnetilmiş oturun. Elleri kalçaların yanına koyun, avuçları yere basın. Dik oturun, karın kaslarını çalıştırın.", Contraindications: []string{}},
	{PoseID: "cat_cow", NameEN: "Cat-Cow Stretch", NameTR: "Kedi-İnek Germe", Category: CategorySeated, Difficulty: 1, TargetArea: "spine", InstructionsEN: "Start on all fours. Inhale, drop belly and lift head (Cow). Exhale, round spine up and tuck chin (Cat). Alternate with breath.", InstructionsTR: "Dört ayak üstü başlayın. Nefes alın, karnı indirin ve başı kaldırın (İnek). Nefes verin, omurgayı yukarı yuvarlayın ve çeneyi içeri çekin (Kedi). Nefesle dönüşümlü tekrarlayın.", Contraindications: []string{}},

	{PoseID: "cobra", NameEN: "Cobra Pose", NameTR: "Kobra Duruşu", Category: CategoryProne, Difficulty: 1, TargetArea: "back", InstructionsEN: "Lie face down, place hands under shoulders. Press up gently, lifting chest while keeping hips on the floor. Elbows slightly bent, shoulders down.", InstructionsTR: "Yüzüstü uzanın, elleri omuzların altına koyun. Karnı yerde tutarak göğsü yukarı kaldırın. Dirsekler hafif bükülü, omuzlar aşağıda.", Contraindications: []string{"herniated_disc", "pregnancy"}},
	{PoseID: "upward_dog", NameEN: "Upward-Facing Dog", NameTR: "Yukarı Bakan Köpek", Category: CategoryProne, Difficulty: 2, TargetArea: "back", InstructionsEN: "From prone position, press hands into floor and straighten arms. Lift thighs and knees off the mat. Open chest, shoulders back and down.", InstructionsTR: "Yüzüstü pozisyondan elleri yere basın ve kolları düzeltin. Uyluk ve dizleri matın üzerinden kaldırın. Göğsü açın, omuzları geri ve aşağı çekin.", Contraindications: []string{"herniated_disc", "wrist_injury"}},
	{PoseID: "sphinx", NameEN: "Sphinx Pose", NameTR: "Sfenks Duruşu", Category: CategoryProne, Difficulty: 1, TargetArea: "back", InstructionsEN: "Lie face down, place forearms on floor with elbows under shoulders. Lift chest gently, keeping lower body relaxed. Hold and breathe deeply.", InstructionsTR: "Yüzüstü uzanın, ön kolları yere koyun, dirsekler omuzların altında. Göğsü hafifçe kaldırın, alt vücudu gevşek tutun. Tutun ve derin nefes alın.", Contraindications: []string{"herniated_disc"}},
	{PoseID: "locust", NameEN: "Locust Pose", NameTR: "Çekirge Duruşu", Category: CategoryProne, Difficulty: 2, TargetArea: "back", InstructionsEN: "Lie face down, arms alongside body. Lift head, chest, arms, and legs off the floor simultaneously. Squeeze glutes and reach back through toes.", InstructionsTR: "Yüzüstü uzanın, kollar vücudun yanında. Baş, göğüs, kollar ve bacakları aynı anda yerden kaldırın. Kalçaları sıkın ve parmak uçlarından geriye uzanın.", Contraindications: []string{"herniated_disc", "pregnancy"}},
	{PoseID: "bow", NameEN: "Bow Pose", NameTR: "Yay Duruşu", Category: CategoryProne, Difficulty: 3, TargetArea: "back", InstructionsEN: "Lie face down, bend knees and reach back to hold ankles. Kick feet into hands to lift chest and thighs. Open chest and look forward.", InstructionsTR: "Yüzüstü uzanın, dizleri bükün ve bilekleri tutmak için geriye uzanın. Ayakları ellere doğru iterek göğsü ve uylukları kaldırın. Göğsü açın ve öne bakın.", Contraindications: []string{"herniated_disc", "pregnancy", "low_back_pain"}},
	{PoseID: "plank", NameEN: "Plank Pose", NameTR: "Plank Duruşu", Category: CategoryProne, Difficulty: 2, TargetArea: "core", InstructionsEN: "Place hands under shoulders, extend legs back. Body forms a straight line from head to heels. Engage core, hold steady and breathe.", InstructionsTR: "Elleri omuzların altına koyun, bacakları geriye uzatın. Vücut baştan topuklara düz bir çizgi oluşturur. Karnı sıkın, sabit tutun ve nefes alın.", Contraindications: []string{"wrist_injury"}},
	{PoseID: "side_plank", NameEN: "Side Plank", NameTR: "Yan Plank", Category: CategoryProne, Difficulty: 3, TargetArea: "core", InstructionsEN: "From Plank, shift weight to one hand and stack feet. Raise opposite arm to ceiling. Keep body in a straight line, engage obliques.", InstructionsTR: "Plank'tan ağırlığı bir ele kaydırın ve ayakları üst üste koyun. Karşı kolu tavana kaldırın. Vücudu düz çizgide tutun, yan karın kaslarını çalıştırın.", Contraindications: []string{"wrist_injury", "shoulder_injury"}},
	{PoseID: "forearm_plank", NameEN: "Forearm Plank", NameTR: "Ön Kol Plank", Category: CategoryProne, Difficulty: 2, TargetArea: "core", InstructionsEN: "Place forearms on floor, elbows under shoulders. Extend legs back, body in a straight line. Hold position, engaging core throughout.", InstructionsTR: "Ön kolları yere koyun, dirsekler omuzların altında. Bacakları geriye uzatın, vücut düz çizgide. Pozisyonu tutun, karnı sürekli sıkın.", Contraindications: []string{}},
	{PoseID: "downward_dog", NameEN: "Downward-Facing Dog", NameTR: "Aşağı Bakan Köpek", Category: CategoryProne, Difficulty: 2, TargetArea: "full_body", InstructionsEN: "From all fours, lift hips up and back forming an inverted V. Press hands into mat, straighten legs and relax head between arms.", InstructionsTR: "Dört ayak üstünden kalçaları yukarı ve geriye kaldırarak ters V oluşturun. Elleri mata basın, bacakları düzeltin ve başı kollar arasında gevşetin.", Contraindications: []string{"wrist_injury", "high_blood_pressure"}},
	{PoseID: "child", NameEN: "Child's Pose", NameTR: "Çocuk Duruşu", Category: CategoryProne, Difficulty: 1, TargetArea: "back", InstructionsEN: "Kneel, sit back on heels, fold forward with arms extended or alongside body. Rest forehead on mat. Breathe deeply and release tension.", InstructionsTR: "Diz çökün, topuklara oturun, kollar uzatılmış veya vücudun yanında öne katlayın. Alnı mata koyun. Derin nefes alın ve gerginliği bırakın.", Contraindications: []string{"knee_injury"}},
	{PoseID: "swimming", NameEN: "Swimming Pose", NameTR: "Yüzme Duruşu", Category: CategoryProne, Difficulty: 2, TargetArea: "back", InstructionsEN: "Lie face down, extend arms forward. Lift opposite arm and leg simultaneously, alternating sides. Keep core engaged throughout the movement.", InstructionsTR: "Yüzüstü uzanın, kolları öne uzatın. Karşılıklı kol ve bacağı aynı anda kaldırarak yer değiştirin. Hareket boyunca karnı sıkı tutun.", Contraindications: []string{"low_back_pain"}},

	{PoseID: "bridge", NameEN: "Bridge Pose", NameTR: "Köprü Duruşu", Category: CategorySupine, Difficulty: 1, TargetArea: "glutes", InstructionsEN: "Lie on back, bend knees with feet flat. Lift hips toward ceiling, clasp hands under back. Press feet and shoulders into mat.", InstructionsTR: "Sırt üstü uzanın, dizleri bükün, ayaklar yerde. Kalçaları tavana doğru kaldırın, elleri sırtın altında kavuşturun. Ayakları ve omuzları mata basın.", Contraindications: []string{"neck_injury"}},
	{PoseID: "supine_twist", NameEN: "Supine Spinal Twist", NameTR: "Sırtüstü Omurga Bükümü", Category: CategorySupine, Difficulty: 1, TargetArea: "spine", InstructionsEN: "Lie on back, draw one knee to chest. Guide knee across body to opposite side, extend arm out. Look opposite direction and relax.", InstructionsTR: "Sırt üstü uzanın, bir dizi göğse çekin. Dizi karşı tarafa doğru yönlendirin, kolu yana uzatın. Ters yöne bakın ve gevşeyin.", Contraindications: []string{"herniated_disc"}},
	{PoseID: "happy_baby", NameEN: "Happy Baby Pose", NameTR: "Mutlu Bebek Duruşu", Category: CategorySupine, Difficulty: 1, TargetArea: "hips", InstructionsEN: "Lie on back, grab outsides of feet with knees bent. Pull knees toward armpits gently. Rock side to side to massage spine.", InstructionsTR: "Sırt üstü uzanın, dizler bükülü halde ayakların dışını tutun. Dizleri koltuk altlarına doğru çekin. Omurgayı masaj etmek için yana sallanın.", Contraindications: []string{"neck_injury", "pregnancy"}},
	{PoseID: "legs_up_wall", NameEN: "Legs Up the Wall", NameTR: "Duvarda Bacaklar", Category: CategorySupine, Difficulty: 1, TargetArea: "legs", InstructionsEN: "Sit next to a wall, swing legs up as you lie back. Rest legs vertically against the wall. Arms at sides, close eyes and breathe.", InstructionsTR: "Duvarın yanında oturun, sırt üstü uzanırken bacakları yukarı kaldırın. Bacakları duvara dikey dayayın. Kollar yanlarda, gözleri kapatın ve nefes alın.", Contraindications: []string{"high_blood_pressure"}},
	{PoseID: "reclined_bound_angle", NameEN: "Reclined Bound Angle", NameTR: "Sırtüstü Bağlı Açı", Category: CategorySupine, Difficulty: 1, TargetArea: "hips", InstructionsEN: "Lie on back, bring soles of feet together and let knees fall open. Arms resting at sides or on belly. Breathe deeply and surrender.", InstructionsTR: "Sırt üstü uzanın, ayak tabanlarını birleştirip dizleri yana açın. Kollar yanlarda veya karnın üzerinde. Derin nefes alın ve teslim olun.", Contraindications: []string{"groin_injury"}},
	{PoseID: "wind_relieving", NameEN: "Wind Relieving Pose", NameTR: "Gaz Giderici Duruş", Category: CategorySupine, Difficulty: 1, TargetArea: "core", InstructionsEN: "Lie on back, hug one or both knees to chest. Rock gently side to side. Keep shoulders and head on the mat.", InstructionsTR: "Sırt üstü uzanın, bir veya iki dizi göğse sarın. Yanlara hafifçe sallanın. Omuzları ve başı matta tutun.", Contraindications: []string{}},
	{PoseID: "corpse", NameEN: "Corpse Pose", NameTR: "Ölü Duruşu (Savasana)", Category: CategorySupine, Difficulty: 1, TargetArea: "full_body", InstructionsEN: "Lie flat on back, legs slightly apart, arms at sides with palms up. Close eyes, relax entire body. Focus only on breathing.", InstructionsTR: "Sırt üstü düz uzanın, bacaklar hafif ayrık, kollar yanlarda avuçlar yukarı. Gözleri kapatın, tüm vücudu gevşetin. Sadece nefese odaklanın.", Contraindications: []string{}},
	{PoseID: "fish", NameEN: "Fish Pose", NameTR: "Balık Duruşu", Category: CategorySupine, Difficulty: 2, TargetArea: "chest", InstructionsEN: "Lie on back, slide hands under hips. Press forearms into floor and lift chest, arching upper back. Top of head may lightly touch floor.", InstructionsTR: "Sırt üstü uzanın, elleri kalçaların altına kaydırın. Ön kolları yere basın ve göğsü kaldırın, üst sırtı kavislendirin. Başın üstü yere hafifçe değebilir.", Contraindications: []string{"neck_injury", "low_back_pain"}},
	{PoseID: "wheel", NameEN: "Wheel Pose", NameTR: "Tekerlek Duruşu", Category: CategorySupine, Difficulty: 5, TargetArea: "back", InstructionsEN: "Lie on back, place hands by ears, fingertips toward shoulders. Press up, straightening arms and lifting entire body into a backbend.", InstructionsTR: "Sırt üstü uzanın, elleri kulakların yanına koyun, parmak uçları omuzlara doğru. Yukarı itin, kolları düzeltin ve tüm vücudu arka eğime kaldırın.", Contraindications: []string{"wrist_injury", "shoulder_injury", "neck_injury", "herniated_disc"}},
	{PoseID: "reclined_hand_to_toe", NameEN: "Reclined Hand-to-Big-Toe", NameTR: "Sırtüstü El-Ayak Parmağı", Category: CategorySupine, Difficulty: 2, TargetArea: "hamstrings", InstructionsEN: "Lie on back, extend one leg up and hold big toe or use a strap. Keep other leg extended on floor. Straighten raised leg without forcing.", InstructionsTR: "Sırt üstü uzanın, bir bacağı yukarı uzatıp ayak parmağını tutun veya kayış kullanın. Diğer bacak yerde uzanır. Kaldırılan bacağı zorlamadan düzeltin.", Contraindications: []string{}},

	{PoseID: "headstand", NameEN: "Headstand", NameTR: "Baş Üstü Duruş", Category: CategoryInversion, Difficulty: 5, TargetArea: "core", InstructionsEN: "Interlace fingers and place forearms on floor. Set crown of head on mat, cradled by hands. Walk feet in and lift legs overhead. Engage core strongly.", InstructionsTR: "Parmakları kenetleyin ve ön kolları yere koyun. Başın tepesini ellerin içine alarak mata koyun. Ayakları yaklaştırın ve bacakları yukarı kaldırın. Karnı güçlü sıkın.", Contraindications: []string{"neck_injury", "high_blood_pressure", "pregnancy", "glaucoma"}},
	{PoseID: "shoulderstand", NameEN: "Shoulderstand", NameTR: "Omuz Üstü Duruş", Category: CategoryInversion, Difficulty: 4, TargetArea: "core", InstructionsEN: "From lying on back, lift legs and hips overhead, supporting lower back with hands. Extend legs straight up, body weight on shoulders and upper arms.", InstructionsTR: "Sırt üstü yatarken bacakları ve kalçaları yukarı kaldırın, alt sırtı ellerle destekleyin. Bacakları düz yukarı uzatın, vücut ağırlığı omuzlar ve üst kollarda.", Contraindications: []string{"neck_injury", "high_blood_pressure", "pregnancy"}},
	{PoseID: "plow", NameEN: "Plow Pose", NameTR: "Saban Duruşu", Category: CategoryInversion, Difficulty: 4, TargetArea: "spine", InstructionsEN: "From Shoulderstand, lower feet toward floor behind head. Keep legs straight and support back with hands if needed. Breathe steadily.", InstructionsTR: "Omuz Üstü Duruş'tan ayakları başın arkasına doğru yere indirin. Bacakları düz tutun ve gerekirse sırtı ellerle destekleyin. Düzenli nefes alın.", Contraindications: []string{"neck_injury", "herniated_disc", "high_blood_pressure"}},
	{PoseID: "forearm_stand", NameEN: "Forearm Stand", NameTR: "Ön Kol Duruşu", Category: CategoryInversion, Difficulty: 5, TargetArea: "shoulders", InstructionsEN: "Place forearms on floor shoulder-width apart. Kick one leg up and bring the other to meet it overhead. Engage core and press forearms firmly down.", InstructionsTR: "Ön kolları omuz genişliğinde yere koyun. Bir bacağı yukarı tekmeleyip diğerini başın üzerinde birleştirin. Karnı sıkın ve ön kolları yere sıkıca basın.", Contraindications: []string{"shoulder_injury", "neck_injury", "high_blood_pressure"}},
	{PoseID: "dolphin", NameEN: "Dolphin Pose", NameTR: "Yunus Duruşu", Category: CategoryInversion, Difficulty: 3, TargetArea: "shoulders", InstructionsEN: "From all fours, place forearms on floor. Lift hips up and back like Downward Dog but on forearms. Walk feet closer and press chest toward thighs.", InstructionsTR: "Dört ayak üstünden ön kolları yere koyun. Kalçaları Aşağı Bakan Köpek gibi yukarı ve geriye kaldırın ama ön kollar üzerinde. Ayakları yaklaştırın ve göğsü uyluklara doğru bastırın.", Contraindications: []string{"shoulder_injury"}},
}

var poseIndex map[string]*Pose

func init() {
	poseIndex = make(map[string]*Pose, len(AllPoses))
	for i := range AllPoses {
		poseIndex[AllPoses[i].PoseID] = &AllPoses[i]
	}
}

func GetPoseByID(id string) (*Pose, bool) {
	p, ok := poseIndex[id]
	return p, ok
}

func GetAllPoses() []Pose {
	return AllPoses
}

func TotalPoseCount() int {
	return len(AllPoses)
}

func AllPoseIDs() []string {
	ids := make([]string, len(AllPoses))
	for i, p := range AllPoses {
		ids[i] = p.PoseID
	}
	return ids
}

func GetSafePoseIDs(injuries []string) []string {
	if len(injuries) == 0 {
		return AllPoseIDs()
	}
	injurySet := make(map[string]bool, len(injuries))
	for _, inj := range injuries {
		injurySet[inj] = true
	}
	var safe []string
	for _, p := range AllPoses {
		blocked := false
		for _, c := range p.Contraindications {
			if injurySet[c] {
				blocked = true
				break
			}
		}
		if !blocked {
			safe = append(safe, p.PoseID)
		}
	}
	return safe
}

func CategoriesWithCounts() map[Category]int {
	counts := make(map[Category]int)
	for _, p := range AllPoses {
		counts[p.Category]++
	}
	return counts
}
